---

- hosts: localhost
  vars:
    home: /host/home
    config: "{{ home }}/.bash_profile"

  tasks:
    - lineinfile:
        dest: "{{ config }}"
        state: present
        create: true
        line: "set -o vi"

    - lineinfile:
        dest: "{{ config }}"
        state: present
        create: true
        regexp: "fixssh"
        line: "alias fixssh='eval $(tmux showenv -s SSH_AUTH_SOCK)'"

    - lineinfile:
        dest: "{{ config }}"
        state: present
        create: true
        line: "export PS1='$(__git_ps1) \\W\\$'"

    - lineinfile:
        dest: "{{ config }}"
        state: present
        create: true
        line: "export PATH=$PATH:~/.local/bin"

    - lineinfile:
        dest: "{{ config }}"
        state: present
        create: true
        line: "export FZF_DEFAULT_COMMAND='fd --no-ignore-vcs --exclude node_modules'"

    - copy:
        src: gitconfig
        dest: "{{ home }}/.gitconfig"
