version: 2
root-markers:
  - .git/
  - pyproject.toml

tools:
  python-flake8: &python-flake8
    lint-command: "flake8 --stdin-display-name ${INPUT} -"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: %m"

  python-mypy: &python-mypy
    lint-command: "mypy --show-column-numbers"
    lint-formats:
      - "%f:%l:%c: %trror: %m"
      - "%f:%l:%c: %tarning: %m"
      - "%f:%l:%c: %tote: %m"

  python-autopep8: &python-autopep8
    format-command: "autopep8 -"
    format-stdin: true

  python-isort: &python-isort
    format-command: "isort --quiet -"
    format-stdin: true

languages:
  python:
    - <<: *python-flake8
    # - <<: *python-autopep8
